version: '3.8'

services:
  # Официальный агент micro-ROS
  uros-agent:
    image: microros/micro-ros-agent:humble
    container_name: uros_agent
    network_mode: host
    restart: always
    command: udp4 --port 8888

  # Наша нода управления на Python
  arm-controller:
    image: mirror.gcr.io/library/ros:humble-ros-base
    container_name: arm_controller
    network_mode: host
    volumes:
      - ../server:/app
    working_dir: /app
    restart: always
    command: bash -c "source /opt/ros/humble/setup.bash && python3 arm_control_node.py"
    depends_on:
      - uros-agent
