version: '3.8'
services:
  uros-agent:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - http_proxy=http://127.0.0.1:8118
        - https_proxy=http://127.0.0.1:8118
    network_mode: host
    environment:
      - http_proxy=http://127.0.0.1:8118
      - https_proxy=http://127.0.0.1:8118
    command: bash -c "source /opt/ros/humble/setup.bash && ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888"
